CREATE TABLE CONTACT_CUSTOMER (contact_customer_id INTEGER NOT NULL, CONTACTCUSTOMEREMAIL VARCHAR(255), CONTACTCUSTOMERFIRSTNAME VARCHAR(255), CONTACTCUSTOMERLASTNAME VARCHAR(255), CONTACTCUSTOMERPHONE VARCHAR(255), CUSTOMERID INTEGER, PRIMARY KEY (contact_customer_id));
CREATE TABLE CUSTOMER (customer_id INTEGER NOT NULL, CUSTOMEREMAIL VARCHAR(255), CUSTOMERFIRSTNAME VARCHAR(255), CUSTOMERLASTNAME VARCHAR(255), CUSTOMERPHONE VARCHAR(255), CUSTOMERTYPEOFINDUSTRY VARCHAR(255), postcode VARCHAR(255), STATE VARCHAR(255), street_address VARCHAR(255), street_number VARCHAR(255), SUBURB VARCHAR(255), PRIMARY KEY (customer_id));
CREATE TABLE CUSTOMER_CONTACT_CUSTOMER (Customer_customer_id INTEGER NOT NULL, customerContactCustomer_contact_customer_id INTEGER NOT NULL, PRIMARY KEY (Customer_customer_id, customerContactCustomer_contact_customer_id));
ALTER TABLE CONTACT_CUSTOMER ADD CONSTRAINT CNTCTCSTOMERcstmrd FOREIGN KEY (customer_id) REFERENCES CUSTOMER (customer_id);
ALTER TABLE CUSTOMER_CONTACT_CUSTOMER ADD CONSTRAINT CSTMRCNCstmrcstmrd FOREIGN KEY (Customer_customer_id) REFERENCES CUSTOMER (customer_id);
ALTER TABLE CUSTOMER_CONTACT_CUSTOMER ADD CONSTRAINT cstmrCntctCstmrcnt FOREIGN KEY (customerContactCustomer_contact_customer_id) REFERENCES CONTACT_CUSTOMER (contact_customer_id);
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);
